// Generated by gencpp from file feature_recon/Person.msg
// DO NOT EDIT!


#ifndef FEATURE_RECON_MESSAGE_PERSON_H
#define FEATURE_RECON_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <feature_recon/BodyPartElm.h>

namespace feature_recon
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : body_part()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : body_part(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::feature_recon::BodyPartElm_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::feature_recon::BodyPartElm_<ContainerAllocator> >::other >  _body_part_type;
  _body_part_type body_part;





  typedef boost::shared_ptr< ::feature_recon::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::feature_recon::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::feature_recon::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::feature_recon::Person > PersonPtr;
typedef boost::shared_ptr< ::feature_recon::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::feature_recon::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::feature_recon::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace feature_recon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'feature_recon': ['/home/alexdupond/DeepLearning/src/feature_recon/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::feature_recon::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::feature_recon::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feature_recon::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::feature_recon::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feature_recon::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::feature_recon::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::feature_recon::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71df5a728503c3e077184dbd734a3f82";
  }

  static const char* value(const ::feature_recon::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71df5a728503c3e0ULL;
  static const uint64_t static_value2 = 0x77184dbd734a3f82ULL;
};

template<class ContainerAllocator>
struct DataType< ::feature_recon::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feature_recon/Person";
  }

  static const char* value(const ::feature_recon::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::feature_recon::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BodyPartElm[] body_part\n\
================================================================================\n\
MSG: feature_recon/BodyPartElm\n\
uint32 part_id\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 confidence\n\
";
  }

  static const char* value(const ::feature_recon::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::feature_recon::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.body_part);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::feature_recon::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::feature_recon::Person_<ContainerAllocator>& v)
  {
    s << indent << "body_part[]" << std::endl;
    for (size_t i = 0; i < v.body_part.size(); ++i)
    {
      s << indent << "  body_part[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::feature_recon::BodyPartElm_<ContainerAllocator> >::stream(s, indent + "    ", v.body_part[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FEATURE_RECON_MESSAGE_PERSON_H
